In [17]:
import pandas as pd
path = "2018_03.csv"
data = pd.read_csv(path)

In [18]:
def order_by_scheduled_time() -> pd.core.frame.DataFrame:
    ordered = data.sort_values(by=['scheduled_time'])
    return ordered

In [19]:
def drop_columns_and_nan() -> pd.core.frame.DataFrame:
    dropped = data.drop(['from'], axis=1)
    dropped = dropped.drop(['to'], axis=1)
    dropped = dropped.dropna()

        return dropped

In [20]:
drop_columns_and_nan()

,date,train_id,stop_sequence,from_id,to_id,scheduled_time,actual_time,delay_minutes,status,line,type
0,2018-03-01,3805,1.0,105,105,2018-03-02 01:22:00,2018-03-02 01:21:05,0.000000,departed,Northeast Corrdr,NJ Transit
1,2018-03-01,3805,2.0,105,38187,2018-03-02 01:31:00,2018-03-02 01:31:08,0.133333,departed,Northeast Corrdr,NJ Transit
2,2018-03-01,3805,3.0,38187,107,2018-03-02 01:40:00,2018-03-02 01:40:07,0.116667,departed,Northeast Corrdr,NJ Transit
3,2018-03-01,3805,4.0,107,37953,2018-03-02 01:45:00,2018-03-02 01:45:10,0.166667,departed,Northeast Corrdr,NJ Transit
4,2018-03-01,3805,5.0,37953,109,2018-03-02 01:49:00,2018-03-02 01:49:10,0.166667,departed,Northeast Corrdr,NJ Transit
...,...,...,...,...,...,...,...,...,...,...,...
256503,2018-03-31,0534,2.0,14,50,2018-03-31 19:02:00,2018-03-31 19:05:07,3.116667,departed,Montclair-Boonton,NJ Transit
256504,2018-03-31,0534,3.0,50,19,2018-03-31 19:05:00,2018-03-31 19:08:06,3.100000,departed,Montclair-Boonton,NJ Transit
256505,2018-03-31,0534,4.0,19,154,2018-03-31 19:07:00,2018-03-31 19:10:11,3.183333,departed,Montclair-Boonton,NJ Transit
256506,2018-03-31,0534,5.0,154,106,2018-03-31 19:13:00,2018-03-31 19:21:02,8.033333,departed,Montclair-Boonton,NJ Transit
256507,2018-03-31,0534,6.0,106,63,2018-03-31 19:38:00,2018-03-31 19:37:00,0.000000,estimated,Montclair-Boonton,NJ Transit

In [21]:
def convert_date_to_day() -> pd.core.frame.DataFrame:
    df_with_day = data
    df_with_day['day'] = pd.to_datetime(df_with_day['date']).dt.day_name()
    df_with_day = df_with_day.drop(['date'], axis=1)
        
    return df_with_day

In [22]:
convert_date_to_day()

,train_id,stop_sequence,from,from_id,to,to_id,scheduled_time,actual_time,delay_minutes,status,line,type,day
0,3805,1.0,New York Penn Station,105,New York Penn Station,105,2018-03-02 01:22:00,2018-03-02 01:21:05,0.000000,departed,Northeast Corrdr,NJ Transit,Thursday
1,3805,2.0,New York Penn Station,105,Secaucus Upper Lvl,38187,2018-03-02 01:31:00,2018-03-02 01:31:08,0.133333,departed,Northeast Corrdr,NJ Transit,Thursday
2,3805,3.0,Secaucus Upper Lvl,38187,Newark Penn Station,107,2018-03-02 01:40:00,2018-03-02 01:40:07,0.116667,departed,Northeast Corrdr,NJ Transit,Thursday
3,3805,4.0,Newark Penn Station,107,Newark Airport,37953,2018-03-02 01:45:00,2018-03-02 01:45:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday
4,3805,5.0,Newark Airport,37953,North Elizabeth,109,2018-03-02 01:49:00,2018-03-02 01:49:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
256503,0534,2.0,Bay Street,14,Glen Ridge,50,2018-03-31 19:02:00,2018-03-31 19:05:07,3.116667,departed,Montclair-Boonton,NJ Transit,Saturday
256504,0534,3.0,Glen Ridge,50,Bloomfield,19,2018-03-31 19:05:00,2018-03-31 19:08:06,3.100000,departed,Montclair-Boonton,NJ Transit,Saturday
256505,0534,4.0,Bloomfield,19,Watsessing Avenue,154,2018-03-31 19:07:00,2018-03-31 19:10:11,3.183333,departed,Montclair-Boonton,NJ Transit,Saturday
256506,0534,5.0,Watsessing Avenue,154,Newark Broad Street,106,2018-03-31 19:13:00,2018-03-31 19:21:02,8.033333,departed,Montclair-Boonton,NJ Transit,Saturday
256507,0534,6.0,Newark Broad Street,106,Hoboken,63,2018-03-31 19:38:00,2018-03-31 19:37:00,0.000000,estimated,Montclair-Boonton,NJ Transit,Saturday

In [25]:
def convert_scheduled_time_to_part_of_the_day() -> pd.core.frame.DataFrame:
        df_new = data
        
        df_new['scheduled_time'] = pd.to_datetime(df_new['scheduled_time'])
        hour = df_new['scheduled_time'].dt.hour
    
        df_new['part_of_the_day'] = hour.apply(lambda x: 'late_night' if 0 <= x < 4 else
                                                 'early_morning' if 4 <= x < 8 else
                                                 'morning' if 8 <= x < 12 else
                                                 'afternoon' if 12 <= x < 16 else
                                                 'evening' if 16 <= x < 20 else 'night')

        df_new = df_new.drop(['scheduled_time'], axis=1)
        return df_new

In [26]:
convert_scheduled_time_to_part_of_the_day()

,date,train_id,stop_sequence,from,from_id,to,to_id,actual_time,delay_minutes,status,line,type,day,part_of_the_day
0,2018-03-01,3805,1.0,New York Penn Station,105,New York Penn Station,105,2018-03-02 01:21:05,0.000000,departed,Northeast Corrdr,NJ Transit,Thursday,late_night
1,2018-03-01,3805,2.0,New York Penn Station,105,Secaucus Upper Lvl,38187,2018-03-02 01:31:08,0.133333,departed,Northeast Corrdr,NJ Transit,Thursday,late_night
2,2018-03-01,3805,3.0,Secaucus Upper Lvl,38187,Newark Penn Station,107,2018-03-02 01:40:07,0.116667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night
3,2018-03-01,3805,4.0,Newark Penn Station,107,Newark Airport,37953,2018-03-02 01:45:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night
4,2018-03-01,3805,5.0,Newark Airport,37953,North Elizabeth,109,2018-03-02 01:49:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256503,2018-03-31,0534,2.0,Bay Street,14,Glen Ridge,50,2018-03-31 19:05:07,3.116667,departed,Montclair-Boonton,NJ Transit,Saturday,evening
256504,2018-03-31,0534,3.0,Glen Ridge,50,Bloomfield,19,2018-03-31 19:08:06,3.100000,departed,Montclair-Boonton,NJ Transit,Saturday,evening
256505,2018-03-31,0534,4.0,Bloomfield,19,Watsessing Avenue,154,2018-03-31 19:10:11,3.183333,departed,Montclair-Boonton,NJ Transit,Saturday,evening
256506,2018-03-31,0534,5.0,Watsessing Avenue,154,Newark Broad Street,106,2018-03-31 19:21:02,8.033333,departed,Montclair-Boonton,NJ Transit,Saturday,evening
256507,2018-03-31,0534,6.0,Newark Broad Street,106,Hoboken,63,2018-03-31 19:37:00,0.000000,estimated,Montclair-Boonton,NJ Transit,Saturday,evening

In [27]:
def convert_delay() -> pd.core.frame.DataFrame:
        df_new = data

        df_new['delay'] = df_new['delay_minutes'].apply(lambda x: 1 if x >= 5 else 0)

        return df_new

In [28]:
convert_delay()

,date,train_id,stop_sequence,from,from_id,to,to_id,scheduled_time,actual_time,delay_minutes,status,line,type,day,part_of_the_day,delay
0,2018-03-01,3805,1.0,New York Penn Station,105,New York Penn Station,105,2018-03-02 01:22:00,2018-03-02 01:21:05,0.000000,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
1,2018-03-01,3805,2.0,New York Penn Station,105,Secaucus Upper Lvl,38187,2018-03-02 01:31:00,2018-03-02 01:31:08,0.133333,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
2,2018-03-01,3805,3.0,Secaucus Upper Lvl,38187,Newark Penn Station,107,2018-03-02 01:40:00,2018-03-02 01:40:07,0.116667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
3,2018-03-01,3805,4.0,Newark Penn Station,107,Newark Airport,37953,2018-03-02 01:45:00,2018-03-02 01:45:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
4,2018-03-01,3805,5.0,Newark Airport,37953,North Elizabeth,109,2018-03-02 01:49:00,2018-03-02 01:49:10,0.166667,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256503,2018-03-31,0534,2.0,Bay Street,14,Glen Ridge,50,2018-03-31 19:02:00,2018-03-31 19:05:07,3.116667,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256504,2018-03-31,0534,3.0,Glen Ridge,50,Bloomfield,19,2018-03-31 19:05:00,2018-03-31 19:08:06,3.100000,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256505,2018-03-31,0534,4.0,Bloomfield,19,Watsessing Avenue,154,2018-03-31 19:07:00,2018-03-31 19:10:11,3.183333,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256506,2018-03-31,0534,5.0,Watsessing Avenue,154,Newark Broad Street,106,2018-03-31 19:13:00,2018-03-31 19:21:02,8.033333,departed,Montclair-Boonton,NJ Transit,Saturday,evening,1
256507,2018-03-31,0534,6.0,Newark Broad Street,106,Hoboken,63,2018-03-31 19:38:00,2018-03-31 19:37:00,0.000000,estimated,Montclair-Boonton,NJ Transit,Saturday,evening,0

In [29]:
def drop_unnecessary_columns() -> pd.core.frame.DataFrame:
        dropped = data.drop(['train_id'], axis=1)
        dropped = dropped.drop(['scheduled_time'], axis=1)
        dropped = dropped.drop(['actual_time'], axis=1)
        dropped = dropped.drop(['delay_minutes'], axis=1)
        
        return dropped

In [30]:
drop_unnecessary_columns()

,date,stop_sequence,from,from_id,to,to_id,status,line,type,day,part_of_the_day,delay
0,2018-03-01,1.0,New York Penn Station,105,New York Penn Station,105,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
1,2018-03-01,2.0,New York Penn Station,105,Secaucus Upper Lvl,38187,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
2,2018-03-01,3.0,Secaucus Upper Lvl,38187,Newark Penn Station,107,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
3,2018-03-01,4.0,Newark Penn Station,107,Newark Airport,37953,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
4,2018-03-01,5.0,Newark Airport,37953,North Elizabeth,109,departed,Northeast Corrdr,NJ Transit,Thursday,late_night,0
...,...,...,...,...,...,...,...,...,...,...,...,...
256503,2018-03-31,2.0,Bay Street,14,Glen Ridge,50,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256504,2018-03-31,3.0,Glen Ridge,50,Bloomfield,19,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256505,2018-03-31,4.0,Bloomfield,19,Watsessing Avenue,154,departed,Montclair-Boonton,NJ Transit,Saturday,evening,0
256506,2018-03-31,5.0,Watsessing Avenue,154,Newark Broad Street,106,departed,Montclair-Boonton,NJ Transit,Saturday,evening,1
256507,2018-03-31,6.0,Newark Broad Street,106,Hoboken,63,estimated,Montclair-Boonton,NJ Transit,Saturday,evening,0

In [32]:
 def save_first_60k(self, path: str):
    first_60k = self.data.head(60000)
    first_60k.to_csv(path_or_buf=path, index=False)

In [33]:
def prep_df(self, path = 'data/NJ.csv'):
    self.order_by_scheduled_time()
    self.drop_columns_and_nan()
    self.convert_date_to_day()
    self.convert_scheduled_time_to_part_of_the_day()
    self.convert_delay()
    self.drop_unnecessary_columns()
    self.save_first_60k(path)